#include<iostream>;
#include<vector>;
using namespace std;
int main(){
    vector<int> v; //You need not mention size
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.push_back(9);
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.push_back(9);
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.push_back(9);
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.push_back(9);
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.push_back(9);
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.push_back(9);
    cout<<"Size is "<<v.size()<<endl;
    cout<<"Capacity is "<<v.capacity()<<endl; 
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    v.pop_back();  
    cout<<"Size is "<<v.size()<<endl;
    cout<<"Capacity is "<<v.capacity(); 
}